// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsbpslfqepbmglnwpnzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYnBzbGZxZXBibWdsbndwbnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTIwODgsImV4cCI6MjA2NjQyODA4OH0.zbcyguLVW5Fmfk0R73xhzOt0dLaFFVUbMFZKD4isH00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);